---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Upload & Get ssh key id
      digital_ocean:
        state: present
        command: ssh
        ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        name: my_computer
      register: info

    - name: Create new Droplet
      digital_ocean:
        state: present
        command: droplet
        name: ssserver
        size_id: s-1vcpu-1gb
        image_id: ubuntu-16-04-x64
        region_id: nyc3
        ipv6: yes
        ssh_key_ids: '{{ info.ssh_key.id }}'
        unique_name: yes
      register: do

    - name: Add new host to inventory
      add_host:
        name: '{{ do.droplet.ip_address }}'
        groups: ssserver
      when: do.droplet is defined

- hosts: ssserver
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: Wait for port 22 to become available
      local_action: "wait_for port=22 host={{ inventory_hostname }} delay=30"

    - name: Install python 2 for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    
    - name: Gather facts
      setup:
  
  tasks:
    - name: Root setup
      include_role:
        name: root-setup
      tag: root


- hosts: ssserver
  remote_user: ss
  gather_facts: no

  tasks:
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: Install shadowsocks-libev
      import_role:
        name: shadowsocks-libev