---
  - name: Install newer kernel
    become: yes
    apt:
      name: linux-generic-hwe-16.04
      install_recommends: yes

  - name: Enable TCP BBR congestion control
    become: yes  
    sysctl:
      name: net.core.default_qdisc
      value: fq
      state: present
      reload: no

  - name: Enable TCP BBR congestion control
    become: yes  
    sysctl:
      name: net.ipv4.tcp_congestion_control
      value: bbr
      state: present
      reload: yes

  - name: Add shadowsocks apt_repository
    become: yes
    apt_repository:
      repo: 'ppa:max-c-lv/shadowsocks-libev'

  - name: Install shadowsocks-libev
    become: yes
    apt:
      name: shadowsocks-libev
      state: latest
      update_cache: yes

  - name: Install simple-obfs building Dependencies
    become: yes
    apt:
      name: '{{ item }}'
      state: latest
      update_cache: yes
      install_recommends: no
    with_items:
      - build-essential
      - autoconf
      - libtool
      - libssl-dev
      - libpcre3-dev
      - libev-dev
      - asciidoc
      - xmlto
      - automake
    
  - name: Clone simple-obfs
    git:
      repo: https://github.com/shadowsocks/simple-obfs.git
      dest: /home/ss/simple-obfs

  - name: Clone simple-obfs submodule
    shell: cd /home/ss/simple-obfs && git submodule update --init --recursive
  
  - name: Compile simple-obfs
    shell: cd /home/ss/simple-obfs && ./autogen.sh && ./configure && make

  - name: Install simple-obfs
    become: yes
    shell: cd /home/ss/simple-obfs && make install

  - name: shadowsocks config
    become: yes
    lineinfile:
      path: /etc/shadowsocks-libev/config.json
      regexp: '.*\"server\".*'
      line: '    "server":["[::0]","0.0.0.0"],'

  - name: shadowsocks config
    become: yes
    lineinfile:
      path: /etc/shadowsocks-libev/config.json
      regexp: '.*\"method\".*'
      line: '    "method":"chacha20-ietf-poly1305", "plugin":"obfs-server", "plugin_opts":"obfs=http"'

  - name: set firewall allow shadowsocks
    become: yes
    ufw:
      rule: allow
      port: 8388
      state: enabled

  - name: start shadowsocks and add to boot
    become: yes
    service:
      state: started
      enabled: yes
      name: shadowsocks-libev
      use: service

  - name: read config file
    shell: cat /etc/shadowsocks-libev/config.json
    register: conf

  - name: print config file
    debug:
      var: conf.stdout      

  - name: Reboot server
    become: yes
    shell: /sbin/shutdown -r +1 "Reboot to upgrade kernel"
    async: 1
    poll: 0
    ignore_errors: yes

  # - name: Wait for port 22 to become available
  #   local_action: "wait_for port=22 host={{ inventory_hostname }} delay=30"  

  # - name: Remove old kernel
  #   become: yes
  #   apt:
  #     autoremove: yes